### ISSUE TITLE
Update Kouvola's lunch menu

### ISSUE THREAD

**Issue by ZapX5** [wilmaplus/foodmenu#7]
Kouvola has moved their lunch menu over to [https://aromimenu.cgisaas.fi/KouvolaAromieMenus/fi-FI/Default/Kouvola](https://aromimenu.cgisaas.fi/KouvolaAromieMenus/fi-FI/Default/Kouvola). Also the logo has been changed.

**Comment by developerfromjokela** [comment]
Kouvola is now up-to-date with new menu. 👍
